"""update table books

Revision ID: 2e2801a8582b
Revises: 2c35179aa1da
Create Date: 2023-02-03 10:02:28.234346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e2801a8582b"
down_revision = "2c35179aa1da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("updated_date", sa.DateTime(), nullable=True))
    op.add_column("books", sa.Column("updated_by", sa.Integer(), nullable=True))
    op.add_column("books", sa.Column("deleted_date", sa.DateTime(), nullable=True))
    op.add_column("books", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "books", "users", ["updated_by"], ["id"])
    op.create_foreign_key(None, "books", "users", ["deleted_by"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_column("books", "deleted_by")
    op.drop_column("books", "deleted_date")
    op.drop_column("books", "updated_by")
    op.drop_column("books", "updated_date")
    # ### end Alembic commands ###
