"""update table books

Revision ID: 3f50e2318328
Revises: 358447271035
Create Date: 2023-02-08 11:16:56.195898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f50e2318328"
down_revision = "358447271035"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("rate", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "rate")
    # ### end Alembic commands ###
