"""update token block list table

Revision ID: 73ed3f7bede2
Revises: 4c7910aee799
Create Date: 2023-02-02 10:18:26.967956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column

# revision identifiers, used by Alembic.
revision = "73ed3f7bede2"
down_revision = "4c7910aee799"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "token_block_list",
        sa.Column("type", sa.String(length=16), nullable=True),
    )
    type = table("token_block_list", column("type"))
    op.execute(type.update().values(type=""))
    op.alter_column("token_block_list", "type", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("token_block_list", "type")
    # ### end Alembic commands ###
