"""add books table migration

Revision ID: ccdb0bd5a47a
Revises: e2e68e5dff12
Create Date: 2023-01-31 16:07:37.813136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ccdb0bd5a47a"
down_revision = "e2e68e5dff12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("author_id", sa.Integer(), nullable=True))
    op.add_column("books", sa.Column("created_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "books", "users", ["author_id"], ["id"])
    op.create_foreign_key(None, "books", "users", ["created_by"], ["id"])
    op.drop_column("books", "author")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column("author", sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_column("books", "created_by")
    op.drop_column("books", "author_id")
    # ### end Alembic commands ###
